#!/usr/bin/env zsh

# produces CSV output from an OFX file

# usage: ofx2csv <ofx_file>

# Prints the transaction date range in the format "YYYY-MM-DD to YYYY-MM-DD"

# Requires the ofx2xml utility, which converts older versions OFX file to XML.
# It can be downloaded from https://github.com/heckman/ofx2xml

# This utility is working (so far) for my accounts, YMMV.
# This utility only handles bank accounts and credit cards,
# other types of accounts will cause an error.

go run ofx2xml.go "$@" |
xq -j |
jq -r '
	.OFX
	| if has("BANKMSGSRSV1") then
		.BANKMSGSRSV1.STMTTRNRS
		| if type == "array" then .[0] else . end
		| .STMTRS
	elif has("CREDITCARDMSGSRSV1") then
		.CREDITCARDMSGSRSV1.CCSTMTTRNRS
		| if type == "array" then .[0] else . end
		| .CCSTMTRS
	else
		error("Unknown OFX type")
	end
	| .BANKTRANLIST
	|
		.DTSTART[0:4]+"-"+.DTSTART[4:6]+"-"+.DTSTART[6:8]
		+ " to " +
		.DTEND[0:4]+"-"+.DTEND[4:6]+"-"+.DTEND[6:8]
'
