#!/usr/bin/env bash
#
# builds compiled binaries

root="$(git rev-parse --show-toplevel)"
[[ "${root##*/}" == 'ofx-txns' ]] || {
	echo "FAIL: should be run within ofx repository."
	exit 1
}
bin="$root/bin"

build_ofx2xml(){
	cd "$root/src/ofx2xml" || return 1
	go build -o "$bin" ofx2xml.go
}

build_ofx2xml && echo "OK: built ofx2xml"

