#!/usr/bin/env bash
#
# builds compiled binaries

# shellcheck disable=SC2015
root="$(git rev-parse --show-toplevel 2>/dev/null)" &&
[[ "$(realpath "$0")" == "$root"* ]] || {
	echo "FAIL: should be run within ofx repository."
	exit 1
}

bin="$root/bin"
mkdir -p "$bin"

build_ofx2xml(){
	cd "$root/src/ofx2xml" || return 1
	go build -o "$bin" ofx2xml.go
}

build_ofx2xml && echo "OK: built ofx2xml"

