#!/usr/bin/env bash
#
# removes compiled binaries

root="$(git rev-parse --show-toplevel)"
[[ "${root##*/}" == 'ofx-txns' ]] || {
	echo "FAIL: should be run within ofx repository."
	exit 1
}
bin="$root/bin"

clean_ofx2xml(){
	rm "$bin/ofx2xml"
}

clean_ofx2xml && echo "OK: removed ofx2xml"

