#!/usr/bin/env bash
#
# installs compiled binaries & scripts

destination="$HOME/bin"

root="$(git rev-parse --show-toplevel)"
[[ "${root##*/}" == 'ofx-txns' ]] || {
	echo "FAIL: should be run within ofx repository."
	exit 1
}
bin="$root/bin"



[[ -d "$destination" ]] || {
	echo "FAIL: destination directory '$destination' does not exist.">&2
	exit 1
}

[[ -e "$bin/ofx2xml" ]] || {
	"$root/dev-bin/build" || {
		echo "FAIL: failed to build ofx2xml." >&2
		exit 1

	}
}

sources=( "$root/ofx2" "$root/ofx2csv" "$bin/ofx2xml" )
sources_string="ofx2, ofx2csv, and ofx2xml"

printf "Prepared to copy %s to %s.\n" "$sources_string" "$destination"
read -p "proceed? (y/n [n]) " -r
if [[ $REPLY =~ ^[Yy] ]]
then
	cp -i "${sources[@]}" "$destination" &&
	{
		echo "OK: installed ofx2, ofx2csv, and ofx2xml to '$destination'."
	}
else
    echo "Installation aborted."
    exit 1
fi


